Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "ueransimvm"
  config.vm.network "private_network", ip:"192.168.56.102" 
  config.vm.synced_folder "data" , "/home/vagrant/"

  
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.cpus = 1
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get -y update
    apt-get install -y gnupg wget tcpdump make gcc g++ libsctp-dev lksctp-tools iproute2 git
    snap install cmake --classic
    cd /home/vagrant/UERANSIM
    rm -fr .git
    git init
    git remote add origin https://github.com/aligungr/UERANSIM
    git fetch 
    git reset --hard origin/master
    ls
    pwd
    cd /home/vagrant/UERANSIM/
    make
  SHELL
end
